version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    rebase-strategy: "disabled"
    labels:
      - dependencies
      - security
    groups:
      actions-rollup:
        patterns:
          - "*"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:20"
      timezone: "UTC"
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    labels:
      - dependencies
      - security
    groups:
      npm-rollup:
        patterns:
          - "*"
    open-pull-requests-limit: 1

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:40"
      timezone: "UTC"
    rebase-strategy: "disabled"
    labels:
      - dependencies
      - security
    groups:
      cargo-rollup:
        patterns:
          - "*"
    open-pull-requests-limit: 1
