package aegispy:runtime;

interface capability {
  record fs-read-input {
    path: string,
  }

  record fs-write-input {
    path: string,
    data-utf8: string,
  }

  record http-get-input {
    url: string,
  }

  record env-get-input {
    key: string,
  }

  record cap-result {
    ok: bool,
    payload-utf8: string,
    error-code: string,
  }

  fs-read: func(input: fs-read-input) -> cap-result;
  fs-write: func(input: fs-write-input) -> cap-result;
  http-get: func(input: http-get-input) -> cap-result;
  env-get: func(input: env-get-input) -> cap-result;
}

world aegispy-runtime {
  import capability;
}

world aegispy {
  export capability;
}
